### ISSUE TITLE
License

### ISSUE THREAD

**Issue by williamswhy** [roostaiyan/CudaSharedPtr#1]
Hi there,

I think this repo is a very good smart pointer wrapper for CUDA and I would like to use it in a project. However, without an open source license, I cannot use it anywhere legally. So I would like to kindly ask that if you can add an open source license to this code if you are intending to let others to use this code. And I'm sorry if that is not your intention. Thank you for your help!

Best,
Williams

**Comment by roostaiyan** [comment]
Hi Dear,

I added an open source license to this project. 
I really appreciate your great comment.

Best regards,
Roostaiyan
